title: "Jithu Gopal"
description: "Jithu Gopal's Blog"
baseurl: ""
url: "https://www.jithugopal.com"

markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

feed:
  path: /feed.xml

author:
  name: Jithu Gopal
  email: mail@jithugopal.com
